<?php

namespace Taler\Http;

const HTTP_STATUS_CODE_SUCCESS = 200;
const HTTP_STATUS_CODE_ACCEPTED = 202;
const HTTP_STATUS_CODE_NO_CONTENT = 204;
const HTTP_STATUS_CODE_MOVED_PERMANENTLY = 301;
const HTTP_STATUS_CODE_FOUND = 302;
const HTTP_STATUS_CODE_SEE_OTHER = 303;
const HTTP_STATUS_CODE_NOT_MODIFIED = 304;
const HTTP_STATUS_CODE_USE_PROXY = 305;
const HTTP_STATUS_CODE_TEMPORARY_REDIRECT = 307;
const HTTP_STATUS_CODE_PERMANENT_REDIRECT = 308;
const HTTP_STATUS_CODE_BAD_REQUEST = 400;
const HTTP_STATUS_CODE_UNAUTHORIZED = 401;
const HTTP_STATUS_CODE_FORBIDDEN = 403;
const HTTP_STATUS_CODE_NOT_FOUND = 404;
const HTTP_STATUS_CODE_METHOD_NOT_ALLOWED = 405;
const HTTP_STATUS_CODE_UNPROCESSABLE_ENTITY = 422;
const HTTP_STATUS_CODE_CONFLICT = 409;
const HTTP_STATUS_CODE_TOO_MANY_REQUESTS = 429;
const HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR = 500;
const HTTP_STATUS_CODE_NOT_IMPLEMENTED = 501;
const HTTP_STATUS_CODE_BAD_GATEWAY = 502;
const HTTP_STATUS_CODE_SERVICE_UNAVAILABLE = 503;
const HTTP_STATUS_CODE_GATEWAY_TIMEOUT = 504;