<?php

namespace Taler\Api\ContractTerms\Dto;

use Taler\Api\Dto\Location;
use Taler\Api\Dto\RelativeTime;
use Taler\Api\Dto\Timestamp;
use Taler\Api\Order\Dto\Merchant;
use Taler\Api\Inventory\Dto\Product;
use Taler\Api\Order\Dto\Amount;
use Taler\Api\Order\Dto\Exchange;

/**
 * DTO for contract terms version 0 data
 * 
 * @see https://docs.taler.net/core/api-common.html
 */
class ContractTermsV0
{
    /**
     * @param Amount $amount Total price for the transaction. The exchange will subtract deposit fees from that amount before transferring it to the merchant.
     * @param Amount $max_fee Maximum total deposit fee accepted by the merchant for this contract. Overrides defaults of the merchant instance.
     * @param string $summary Human-readable description of the whole purchase
     * @param string $order_id Unique, free-form identifier for the proposal
     * @param array<int, Product> $products List of products that are part of the purchase
     * @param Timestamp $timestamp Time when this contract was generated
     * @param Timestamp $refund_deadline After this deadline has passed, no refunds will be accepted
     * @param Timestamp $pay_deadline After this deadline, the merchant won't accept payments for the contract
     * @param Timestamp $wire_transfer_deadline Transfer deadline for the exchange
     * @param string $merchant_pub Merchant's public key used to sign this proposal
     * @param string $merchant_base_url Base URL of the (public!) merchant backend API
     * @param Merchant $merchant More info about the merchant
     * @param string $h_wire The hash of the merchant instance's wire details
     * @param string $wire_method Wire transfer method identifier for the wire method associated with h_wire
     * @param array<int, Exchange> $exchanges Exchanges that the merchant accepts
     * @param string $nonce Nonce generated by the wallet and echoed by the merchant
     * @param array<string, string>|null $summary_i18n Map from IETF BCP 47 language tags to localized summaries
     * @param string|null $public_reorder_url URL where the same contract could be ordered again
     * @param string|null $fulfillment_url URL that will show that the order was successful after it has been paid for
     * @param string|null $fulfillment_message Message shown to the customer after paying for the order
     * @param array<string, string>|null $fulfillment_message_i18n Map from IETF BCP 47 language tags to localized fulfillment messages
     * @param Location|null $delivery_location Delivery location for (all!) products
     * @param Timestamp|null $delivery_date Time indicating when the order should be delivered
     * @param RelativeTime|null $auto_refund Specifies for how long the wallet should try to get an automatic refund
     * @param object|null $extra Extra data that is only interpreted by the merchant frontend
     * @param int|null $minimum_age Minimum age the buyer must have (in years)
     * @param int|null $version Defaults to version 0.
     */
    public function __construct(
        public readonly Amount $amount,
        public readonly Amount $max_fee,
        public readonly string $summary,
        public readonly string $order_id,
        public readonly array $products,
        public readonly Timestamp $timestamp,
        public readonly Timestamp $refund_deadline,
        public readonly Timestamp $pay_deadline,
        public readonly Timestamp $wire_transfer_deadline,
        public readonly string $merchant_pub,
        public readonly string $merchant_base_url,
        public readonly Merchant $merchant,
        public readonly string $h_wire,
        public readonly string $wire_method,
        public readonly array $exchanges,
        public readonly string $nonce,
        public readonly ?array $summary_i18n = null,
        public readonly ?string $public_reorder_url = null,
        public readonly ?string $fulfillment_url = null,
        public readonly ?string $fulfillment_message = null,
        public readonly ?array $fulfillment_message_i18n = null,
        public readonly ?Location $delivery_location = null,
        public readonly ?Timestamp $delivery_date = null,
        public readonly ?RelativeTime $auto_refund = null,
        public readonly ?object $extra = null,
        public readonly ?int $minimum_age = null,
        public readonly ?int $version = 0,
    ) {
    }

    /**
     * Creates a new instance from an array of data
     *
     * @param array{
     *     amount: string,
     *     max_fee: string,
     *     summary: string,
     *     order_id: string,
     *     products: array<int, array{
     *         description: string,
     *         product_id?: string|null,
     *         description_i18n?: array<string, string>|null,
     *         quantity?: int|null,
     *         unit?: string|null,
     *         price?: string|null,
     *         image?: string|null,
     *         taxes?: array<int, array{name: string, tax: string}>|null,
     *         delivery_date?: array{t_s: int|string}|null
     *     }>,
     *     timestamp: array{t_s: int|string},
     *     refund_deadline: array{t_s: int|string},
     *     pay_deadline: array{t_s: int|string},
     *     wire_transfer_deadline: array{t_s: int|string},
     *     merchant_pub: string,
     *     merchant_base_url: string,
     *     merchant: array{
     *         name: string,
     *         email?: string|null,
     *         website?: string|null,
     *         logo?: string|null,
     *         address?: array{
     *             country?: string|null,
     *             town?: string|null,
     *             state?: string|null,
     *             region?: string|null,
     *             province?: string|null,
     *             street?: string|null
     *         }|null,
     *         jurisdiction?: array{
     *             country?: string|null,
     *             town?: string|null,
     *             state?: string|null,
     *             region?: string|null,
     *             province?: string|null,
     *             street?: string|null
     *         }|null
     *     },
     *     h_wire: string,
     *     wire_method: string,
     *     exchanges: array<int, array{
     *         url: string,
     *         priority: int,
     *         master_pub: string,
     *         max_contribution?: string|null
     *     }>,
     *     nonce: string,
     *     summary_i18n?: array<string, string>|null,
     *     public_reorder_url?: string|null,
     *     fulfillment_url?: string|null,
     *     fulfillment_message?: string|null,
     *     fulfillment_message_i18n?: array<string, string>|null,
     *     delivery_location?: array{
     *         country?: string|null,
     *         town?: string|null,
     *         state?: string|null,
     *         region?: string|null,
     *         province?: string|null,
     *         street?: string|null
     *     }|null,
     *     delivery_date?: array{t_s: int|string}|null,
     *     auto_refund?: array{d_us: int|string}|null,
     *     extra?: object|null,
     *     minimum_age?: int|null,
     *     version?: int|null
     * } $data
     */
    public static function createFromArray(array $data): self
    {
        return new self(
            amount: new Amount($data['amount']),
            max_fee: new Amount($data['max_fee']),
            summary: $data['summary'],
            order_id: $data['order_id'],
            products: array_map(
                static fn (array $product) => Product::createFromArray($product),
                $data['products']
            ),
            timestamp: Timestamp::createFromArray($data['timestamp']),
            refund_deadline: Timestamp::createFromArray($data['refund_deadline']),
            pay_deadline: Timestamp::createFromArray($data['pay_deadline']),
            wire_transfer_deadline: Timestamp::createFromArray($data['wire_transfer_deadline']),
            merchant_pub: $data['merchant_pub'],
            merchant_base_url: $data['merchant_base_url'],
            merchant: Merchant::createFromArray($data['merchant']),
            h_wire: $data['h_wire'],
            wire_method: $data['wire_method'],
            exchanges: array_map(
                static fn (array $exchange) => Exchange::createFromArray($exchange),
                $data['exchanges']
            ),
            nonce: $data['nonce'],
            summary_i18n: $data['summary_i18n'] ?? null,
            public_reorder_url: $data['public_reorder_url'] ?? null,
            fulfillment_url: $data['fulfillment_url'] ?? null,
            fulfillment_message: $data['fulfillment_message'] ?? null,
            fulfillment_message_i18n: $data['fulfillment_message_i18n'] ?? null,
            delivery_location: isset($data['delivery_location']) ? Location::createFromArray($data['delivery_location']) : null,
            delivery_date: isset($data['delivery_date']) ? Timestamp::createFromArray($data['delivery_date']) : null,
            auto_refund: isset($data['auto_refund']) ? RelativeTime::createFromArray($data['auto_refund']) : null,
            extra: $data['extra'] ?? null,
            minimum_age: $data['minimum_age'] ?? null,
            version: $data['version'] ?? 0
        );
    }
} 